name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Workflow
    runs-on: ubuntu-latest
    environment: te
    steps:
      - name: Hello
        run: |
          echo "Hello"
