name: Test Workflow

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: read

jobs:
  test:
    name: Test Workflow
    runs-on: ubuntu-latest
    environment: testtest
    steps:
      - name: Hello
        run: |
          echo "Hello"
